schema_version: 1

context:
  version: "7.0.0"
  python_min: "3.11"

package:
  name: tuf
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tuf/tuf-${{ version }}.tar.gz
  sha256: 9d2e6723538e0d5a3e482b6de805fcfe64481448d5853039ba6b06ba541efd7f

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling ==1.27.0
    - pip
  run:
    - python >=${{ python_min }}
    - securesystemslib >=1.0,<2.dev0
    - urllib3 <3,>=1.21.1

tests:
  - python:
      imports:
        - tuf
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A secure updater framework for Python
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE
    - LICENSE-MIT
  homepage: https://www.updateframework.com
  repository: https://github.com/theupdateframework/python-tuf
  documentation: https://theupdateframework.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - travishathaway
    - jezdez
